### ISSUE TITLE
Number of connections increasing since v4

### ISSUE THREAD

**Issue by richie3366** [meritt/easymongo#5]
Hello there,

I have been using easymongo for a while, it's a great tool, congrats for making it and maintaining it.
But I noticed that the total number of opened connections to the mongodb server was increasing on every request (five by five). These connections were keeping the connection until the interruption of the node process. 

I downgraded easymongo to the 3.3.3 version (with the same code in my app) and the problem did not occur, so I believe that is probably an API change in the mongodb dependency that your did not take in count.

So I'm going to use the v3.3.3 until this issue is solved.
Thank you again.

**Comment by meritt** [comment]
Fix 537f823874e8f5b194fd8828bf08efe4b374f43a
